fix: migrate proxy pooling activity to project activity
I fixed this because since bumping the platform version we were getting an exception on startup about a required migration.

Solves:
com.intellij.diagnostic.PluginException: Migrate com.github.continuedev.continueintellijextension.proxy.ProxyPoolingActivity to ProjectActivity [Plugin: com.github.continuedev.continueintellijextension]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:275)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)

Note: the new activity is asynchronous, so we don't need to create our own coroutine scope for polling the settings.

I tested this feature manually (change in settings is properly recognized & binary restarts on apply).